site_name: 荣品开发板文档

nav:
    - Home: index.md
    - Linux:
        - Linux: Linux文档.md
    - Amlogic:
        - Amlogic: Amlogic文档.md


theme:
    name: readthedocs
    highlightjs: true
    locale: zh
    search_box: true
    hljs_languages:
        - yaml
        - rust




plugins:
    - search:
        lang: 'zh_CN'
        separator: '[\s\-\.]+'
        #prebuild_index: true
        indexing: 'full'
        min_search_length: 2
        

markdown_extensions:
    def_list: {}
    toc:
        permalink: true
        permalink: 
        separator: "_"
    admonition: {}