# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = '嵌入式笔记'
copyright = '2023, JZ Loh'
author = ' JZ Loh'

release = '0.0.1'

# -- General configuration ---------------------------------------------------
# The master toctree document.
master_doc = 'index'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'myst_parser',
    'sphinx_copybutton',
    'sphinx.ext.autosectionlabel',
    'sphinx.ext.viewcode',
    'sphinx_search.extension',
    "sphinx.ext.autodoc",
    "sphinx.ext.intersphinx",
    "sphinx_design",
    "sphinxext.rediraffe",
    "sphinxcontrib.mermaid",
    "sphinxext.opengraph",
]

myst_enable_extensions = ['colon_fence']
myst_heading_anchors = 3

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:

source_suffix = {
    '.rst': 'restructuredtext',
    '.txt': 'markdown',
    '.md': 'markdown',
}


#Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'zh_CN'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
#html_theme = "sphinx_book_theme"
#html_logo = "_static/logo-wide.svg"
#html_favicon = "_static/logo-square.svg"
#html_title = ""
#html_theme_options = {
#    "home_page_in_toc": True,
#    "github_url": "https://github.com/executablebooks/MyST-Parser",
#    "repository_url": "https://github.com/executablebooks/MyST-Parser",
#    "repository_branch": "master",
#    "path_to_docs": "docs",
#    "use_repository_button": True,
#    "use_edit_page_button": True,
#}
#
#myst_enable_extensions = [
#    "dollarmath",
#    "amsmath",
#    "deflist",
#    "fieldlist",
#    "html_admonition",
#    "html_image",
#    "colon_fence",
#    "smartquotes",
#    "replacements",
#    "linkify",
#    "strikethrough",
#    "substitution",
#    "tasklist",
#]
#myst_number_code_blocks = ["typescript"]
#myst_heading_anchors = 2
#myst_footnote_transition = True
#myst_dmath_double_inline = True


# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

html_css_files = [
    'css/custom.css',
]

html_js_files = [
    'js/custom.js',
]
html_search_language = 'zh'

#html_style = 'css/yourtheme.css'

# LaTeX
#latex_engine = 'xelatex'
#latex_use_xindy = False
#latex_elements = {
#    'preamble': '\\usepackage[UTF8]{ctex}\n',
#}
